services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    bind:
      $suplaUrl: '%supla_url%'
      $recaptchaSecret: '%recaptcha_secret%'

  _instanceof:
    SuplaBundle\ParamConverter\AbstractBodyParamConverter:
      tags: [request.param_converter]
    SuplaBundle\Model\ChannelActionExecutor\SingleChannelActionExecutor:
      tags: [supla.channel_action_executor]
    SuplaBundle\Model\ChannelParamsUpdater\SingleChannelParamsUpdater:
      tags: [supla.channel_params_updater]
    SuplaBundle\Model\ChannelStateGetter\SingleChannelStateGetter:
      tags: [supla.channel_state_getter]
    SuplaBundle\Command\Cyclic\CyclicCommand:
      tags: [supla.cyclic_command]

  Doctrine\ORM\EntityManager: '@doctrine.orm.default_entity_manager'
  Doctrine\ORM\EntityManagerInterface: '@doctrine.orm.default_entity_manager'
  Symfony\Component\Serializer\Mapping\Factory\ClassMetadataFactoryInterface: '@serializer.mapping.class_metadata_factory'

  SuplaBundle\Command\:
    resource: '../../src/SuplaBundle/Command'
  SuplaBundle\Command\Cyclic\DispatchCyclicTasksCommand:
    - !tagged supla.cyclic_command
  SuplaBundle\Command\Cyclic\DeleteNotConfirmedUsersCommand:
    $deleteOlderThanHours: '%supla.maintenance.delete_non_confirmed_users_older_than_hours%'
  SuplaBundle\Command\Cyclic\ClearObsoleteAuditEntriesCommand:
    $deleteOlderThanDays: '%supla.maintenance.delete_audit_entries_older_than_days%'

  SuplaBundle\Controller\:
    resource: '../../src/SuplaBundle/Controller'
    public: true

  SuplaBundle\Controller\Api\ServerController:
    $suplaServerHost: '%supla_server%'
    $suplaVersion: '%supla.version%'
    $actAsBrokerCloud: '%act_as_broker_cloud%'

  SuplaBundle\Controller\Api\UserController:
    $clientsRegistrationEnableTime: '%supla.clients_registration.registration_active_time.manual%'
    $ioDevicesRegistrationEnableTime: '%supla.io_devices_registration.registration_active_time.manual%'
    $requireRegulationsAcceptance: '%supla_require_regulations_acceptance%'
    $recaptchaEnabled: '%recaptcha_enabled%'
    $availableLanguages: '%supla.available_languages%'

  SuplaBundle\Controller\ExecuteDirectLinkController:
    $logger: '@monolog.logger.supla_direct_links'

  SuplaBundle\Controller\OAuth\BrokerAuthorizeController:
    public: true
    arguments:
      $authorizeForm: '@fos_oauth_server.authorize.form'
      $authorizeFormHandler: '@fos_oauth_server.authorize.form.handler.default'

  SuplaBundle\Model\:
    resource: '../../src/SuplaBundle/Model'

  SuplaBundle\Model\LocalSuplaCloud:
    $address: '%supla_url%'

  SuplaBundle\Model\UserManager:
    $defaultClientsRegistrationTime: '%supla.clients_registration.registration_active_time.initial%'
    $defaultIoDevicesRegistrationTime: '%supla.io_devices_registration.registration_active_time.initial%'

  SuplaBundle\Model\Schedule\SchedulePlanners\CompositeSchedulePlanner:
    $planners:
      - '@SuplaBundle\Model\Schedule\SchedulePlanners\IntervalSchedulePlanner'
      - '@SuplaBundle\Model\Schedule\SchedulePlanners\SunriseSunsetSchedulePlanner'
      - '@SuplaBundle\Model\Schedule\SchedulePlanners\CronExpressionSchedulePlanner'

  SuplaBundle\Model\ChannelActionExecutor\ChannelActionExecutor:
    - !tagged supla.channel_action_executor

  SuplaBundle\Model\ChannelParamsUpdater\ChannelParamsUpdater:
    - !tagged supla.channel_params_updater

  SuplaBundle\Model\ChannelStateGetter\ChannelStateGetter:
    - !tagged supla.channel_state_getter

  SuplaBundle\Model\Audit\FailedAuthAttemptsUserBlocker:
    $enabled: '%supla.brute_force_auth_prevention.enabled%'
    $maxFailedAttempts: '%supla.brute_force_auth_prevention.max_failed_attempts%'
    $blockTimeInSeconds: '%supla.brute_force_auth_prevention.block_time_seconds%'


  SuplaBundle\Supla\:
    resource: '../../src/SuplaBundle/Supla'

  SuplaBundle\Supla\SuplaServerMock:
    tags:
      - {name: monolog.logger, channel: supla_server}
  SuplaBundle\Supla\SuplaServerReal:
    arguments:
      $socketPath: '%supla_server_socket%'
    tags:
      - {name: monolog.logger, channel: supla_server}

  SuplaBundle\Supla\SuplaAutodiscoverMock:
    tags:
      - {name: monolog.logger, channel: supla_autodiscover}


  SuplaBundle\Supla\SuplaAutodiscoverReal:
    arguments:
      $autodiscoverUrl: "%supla.autodiscover_url%"
      $actAsBrokerCloud: '%act_as_broker_cloud%'
    tags:
      - {name: monolog.logger, channel: supla_autodiscover}

  SuplaBundle\Twig\WebpackAssetVersionStrategy:
    arguments:
      - "%use_webpack_dev_server%"
      - "%supla.webpack_hashes%"

  SuplaBundle\Auth\Voter\:
    resource: '../../src/SuplaBundle/Auth/Voter'

  SuplaBundle\Auth\UserProvider: ~
  SuplaBundle\Auth\UserLoginAttemptListener:
    tags:
      - { name: kernel.event_listener, event: security.authentication.failure, method: onInteractiveAuthenticationFailure }
      - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveAuthenticationSuccess }

  SuplaBundle\Auth\SuplaOAuthStorage:
    $userProvider: '@SuplaBundle\Auth\UserProvider'

  SuplaBundle\Auth\OAuthEventListener:
    tags:
      - { name: kernel.event_listener, event: fos_oauth_server.pre_authorization_process, method: onPreAuthorizationProcess }
      - { name: kernel.event_listener, event: fos_oauth_server.post_authorization_process, method: onPostAuthorizationProcess }

  SuplaBundle\EventListener\ApiExceptionHandler:
    arguments:
      - "%kernel.debug%"
    tags:
      - { name: kernel.event_subscriber }

  SuplaBundle\EventListener\UnavailableInMaintenanceRequestListener:
    arguments:
      $maintenanceMode: "%supla.maintenance_mode%"
    tags:
      - { name: kernel.event_listener, event: kernel.controller, method: onKernelController}

  SuplaBundle\ParamConverter\:
    resource: '../../src/SuplaBundle/ParamConverter'

  SuplaBundle\Serialization\:
    resource: '../../src/SuplaBundle/Serialization'

  SuplaBundle\Mailer\SuplaMailer:
    $mailerFrom: "%mailer_from%"
    $adminEmail: "%admin_email%"
    $defaultLocale: "%locale%"

  SuplaBundle\Twig\FrontendConfig: ~

  SuplaBundle\Repository\AccessIdRepository:
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments: [SuplaBundle\Entity\AccessID]

  SuplaBundle\Repository\AccessTokenRepository:
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments: [SuplaBundle\Entity\OAuth\AccessToken]

  SuplaBundle\Repository\ApiClientRepository:
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments: [SuplaBundle\Entity\OAuth\ApiClient]

  SuplaBundle\Repository\ApiClientAuthorizationRepository:
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments: [SuplaBundle\Entity\OAuth\ApiClientAuthorization]

  SuplaBundle\Repository\AuditEntryRepository:
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments: [SuplaBundle\Entity\AuditEntry]

  SuplaBundle\Repository\ChannelGroupRepository:
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments: [SuplaBundle\Entity\IODeviceChannelGroup]

  SuplaBundle\Repository\UserIconRepository:
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments: [SuplaBundle\Entity\UserIcon]

  SuplaBundle\Repository\ClientAppRepository:
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments: [SuplaBundle\Entity\ClientApp]

  SuplaBundle\Repository\LocationRepository:
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments: [SuplaBundle\Entity\Location]

  SuplaBundle\Repository\ScheduleRepository:
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments: [SuplaBundle\Entity\Schedule]

  SuplaBundle\Repository\UserRepository:
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments: [SuplaBundle\Entity\User]

  SuplaBundle\Repository\IODeviceRepository:
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments: [SuplaBundle\Entity\IODevice]

  SuplaBundle\Repository\IODeviceChannelRepository:
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments: [SuplaBundle\Entity\IODeviceChannel]

  SuplaBundle\Repository\AmazonAlexaRepository:
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments: [SuplaBundle\Entity\AmazonAlexa]

  SuplaBundle\Repository\GoogleHomeRepository:
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments: [SuplaBundle\Entity\GoogleHome]

  SuplaBundle\Auth\SuplaOAuth2:
    arguments:
      - '@fos_oauth_server.storage'
      - '%fos_oauth_server.server.options%'
      - '%supla.oauth.tokens_lifetime%'

  fos_oauth_server.server: '@SuplaBundle\Auth\SuplaOAuth2'
  OAuth2\OAuth2: '@SuplaBundle\Auth\SuplaOAuth2'
