services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  SuplaDeveloperBundle\Command\:
    resource: '../../Command'

  SuplaDeveloperBundle\DataFixtures\ORM\:
    resource: '../../DataFixtures/ORM'
